# Generated by Django 3.2.7 on 2021-10-31 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 12, 49, 35, 943627, tzinfo=utc), verbose_name='date end'),
        ),
    ]
